// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjwOeDgLy8Qq-MV1-nO72E80nFNbsBT-M',
    appId: '1:939486036920:web:98785b7268810feb30854d',
    messagingSenderId: '939486036920',
    projectId: 'pupusas-track',
    authDomain: 'pupusas-track.firebaseapp.com',
    storageBucket: 'pupusas-track.firebasestorage.app',
    measurementId: 'G-XH62JYE1JY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9Tzb9ZoK4XZWbLkmzO2__0R9odG-mEMs',
    appId: '1:939486036920:android:e4ed6801bf95deea30854d',
    messagingSenderId: '939486036920',
    projectId: 'pupusas-track',
    storageBucket: 'pupusas-track.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0TP4gyNh4DY7LbzxaPGplj-RKflQ8h8Q',
    appId: '1:939486036920:ios:7901ca0b5e26c92130854d',
    messagingSenderId: '939486036920',
    projectId: 'pupusas-track',
    storageBucket: 'pupusas-track.firebasestorage.app',
    iosBundleId: 'com.example.pupusasTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0TP4gyNh4DY7LbzxaPGplj-RKflQ8h8Q',
    appId: '1:939486036920:ios:7901ca0b5e26c92130854d',
    messagingSenderId: '939486036920',
    projectId: 'pupusas-track',
    storageBucket: 'pupusas-track.firebasestorage.app',
    iosBundleId: 'com.example.pupusasTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjwOeDgLy8Qq-MV1-nO72E80nFNbsBT-M',
    appId: '1:939486036920:web:8510e8c5b0b193eb30854d',
    messagingSenderId: '939486036920',
    projectId: 'pupusas-track',
    authDomain: 'pupusas-track.firebaseapp.com',
    storageBucket: 'pupusas-track.firebasestorage.app',
    measurementId: 'G-ZKFEG2PK4K',
  );

}